### ISSUE TITLE
Unknown input plugin 'proxysql-query-log'

### ISSUE THREAD

**Issue by v0112358** [takaishi/fluent-plugin-proxysql-query-log#17]
Hi,

I'm testing your plugin and have found the error:
```
# /opt/td-agent/embedded/bin/fluent-plugin-config-format input proxysql-query-log
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/registry.rb:48:in `lookup': Unknown input plugin 'proxysql-query-log'. Run 'gem search -rd fluent-plugin' to find plugins (Fluent::ConfigError)
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:146:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:100:in `new_input'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/command/plugin_config_formatter.rb:53:in `call'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/bin/fluent-plugin-config-format:5:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluent-plugin-config-format:23:in `load'
	from /opt/td-agent/embedded/bin/fluent-plugin-config-format:23:in `<main>'
```
Is this plugin compatible with fluentd 1.2.6?

**Comment by v0112358** [comment]
Hi,

In your code:
```
module Fluent
  module Plugin
    class ProxysqlQueryLogInput < Fluent::Plugin::Input
      Fluent::Plugin.register_input("proxysql_query_log", self)
```
You registered the plugin as being `proxysql_query_log`. I ran again the command `/opt/td-agent/embedded/bin/fluent-plugin-config-format input proxysql_query_log` and everything is working now.

**Comment by ktugan** [comment]
@takaishi could you update the README to change the command? I was struggling for multiple hours with his :)
